<?php
         $record = $block->getEditRecord();
         
    ?>        
        
        
        <form method="POST" action="<?= $this->getUrl('crud/index/save'); ?>" id="id" role="form" name="RegForm" enctype="multipart/form-data" >
                <h2>Form</h2>
                <input type="hidden" name="editRecordId" id="editRecordId" value="<?= $record['post_id']; ?>" />

                <label class="control-label">Name</label>

<input id="name" name="name" value=<?= $record['name'] ?> type="text" class="form-control" data-validate='{"required":true}'>
<button type="submit" title="Submit" id="mcf-btn" class="action submit primary" >
                        <span>Submit</span>
</button>
</form>